### PR TITLE
Use #class_attribute instead of #attr_accessor

### PR DESCRIPTION
**Pull request by avokhmin**
See: https://github.com/rails/rails/blob/v5.0.0.1/activejob/lib/active_job/queue_priority.rb#L29-L33

Also, it prevents wrong data in inherited classes.

### CODE REVIEW

**Comment by avokhmin** [comment]
@nickelser something wrong here?

**Comment by nickelser** [comment]
@avokhmin for some reason I had unwatched my own repository, so I missed out on this PR; many apologies! This is a great catch and I'll merge/release ASAP.

**Comment by nickelser** [comment]
Release v0.1.2 (https://github.com/nickelser/activejob-traffic_control/releases/tag/v0.1.2)

**Comment by avokhmin** [comment]
@nickelser , thanks 👍

**Pull request merged**
